Repository capstone-cookings/BE, pull requests merged in 2025-06, with the labels that each got.

#183 🌏 Deploy[#181] 배포
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientUpdateDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :earth_asia: Deploy

#185 ✨ : Ref[#184] 프로필 이미지 삭제 API 구현
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
Labels: :sparkles: Feature

#186 Deploy [#184] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
Labels: :earth_asia: Deploy

#188 :hammer: Ref[#187] 게시글 전체 조회 api 수정
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :hammer: Refactor

#189 🌏 Deploy [#187] 배포
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :earth_asia: Deploy

#196 :hammer: Ref[#195] 레시피 중복 저장 에러 메시지 변경
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
Labels: :hammer: Refactor

#199 :sparkles:feat[#198] FCM 식재료 소비기한 예약 알림 구현
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/notification/services/FcmService.java
  src/main/java/com/cook/cookapp/ingredient/controller/NotificationController.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientNotificationDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Enum/NotificationStatus.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/entity/IngredientNotification.java
  src/main/java/com/cook/cookapp/ingredient/repository/IngredientNotificationScheduleRepository.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientNotificationService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#201 Update IngredientNotificationService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientNotificationService.java
Labels: :earth_asia: Deploy

#203 🌎 Deploy [#198] 배포
  src/main/java/com/cook/cookapp/ingredient/controller/NotificationController.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientNotificationService.java
Labels: :earth_asia: Deploy

#205 :hammer: Ref[#204] 레시피 저장시 중복 저장 방지 로직 구현
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
Labels: :hammer: Refactor

#206 🌏 Deploy [#204] 배포
  src/main/java/com/cook/cookapp/ingredient/service/IngredientNotificationService.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
Labels: :earth_asia: Deploy

#207 :hammer:ref [#198] 채팅방 참여자 조회 정보 수정
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
Labels: :hammer: Refactor

#208 🌍 Deploy [#198] 수정 사항 배포
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
Labels: :earth_asia: Deploy

#210 🌍 Deploy [#198] 식재료 소비기한 알림 메시지 수정
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientNotificationDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/IngredientNotification.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientNotificationService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :earth_asia: Deploy

#211 Update ChatMessageHandler.java
  src/main/java/com/cook/cookapp/chat/socket/ChatMessageHandler.java
Labels: :earth_asia: Deploy
