Repository capstone-cookings/BE, pull requests merged in 2025-03, with the labels that each got.

#3 ✨ Feat [#2] 초기 세팅
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/cook/cookapp/CookappApplication.java
  src/main/java/com/cook/cookapp/apiPayload/ApiResponse.java
  src/main/java/com/cook/cookapp/apiPayload/code/BaseCode.java
  src/main/java/com/cook/cookapp/apiPayload/code/BaseErrorCode.java
  src/main/java/com/cook/cookapp/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/cook/cookapp/apiPayload/code/ReasonDTO.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/GeneralException.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/handler/UserHandler.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/common/JacksonConfig.java
  src/main/java/com/cook/cookapp/common/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/cook/cookapp/global/BaseEntity.java
  src/main/java/com/cook/cookapp/global/RootController.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: :sparkles: Feature, :gear: Setting

#5 :sparkles: Feat [#4] 엔티티 생성
  src/main/java/com/cook/cookapp/storedFoods/controller/storedFoodsController.java
  src/main/java/com/cook/cookapp/storedFoods/converter/storedFoodsConverter.java
  src/main/java/com/cook/cookapp/storedFoods/dto/req/storedFoodsDtoReq.java
  src/main/java/com/cook/cookapp/storedFoods/dto/res/storedFoodsDtoRes.java
  src/main/java/com/cook/cookapp/storedFoods/entity/storedFoods.java
  src/main/java/com/cook/cookapp/storedFoods/repository/storedFoodsRepository.java
  src/main/java/com/cook/cookapp/storedFoods/service/storedFoodsService.java
  src/main/java/com/cook/cookapp/user/controller/userController.java
  src/main/java/com/cook/cookapp/user/converter/userConverter.java
  src/main/java/com/cook/cookapp/user/dto/req/userDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/userDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/user.java
  src/main/java/com/cook/cookapp/user/repository/userRepository.java
  src/main/java/com/cook/cookapp/user/service/userService.java
  src/main/java/com/cook/cookapp/user/service/userServiceImpl.java
  src/main/resources/application-local.yml
Labels: :sparkles: Feature

#6 :sparkles: Feat [#4] 엔티티 속성 생성
  src/main/java/com/cook/cookapp/storedFoods/entity/Enum/AlarmStatus.java
  src/main/java/com/cook/cookapp/storedFoods/entity/storedFoods.java
  src/main/java/com/cook/cookapp/user/entity/user.java
Labels: :sparkles: Feature

#8 🔨 Ref [#4] 엔티티 수정
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/converter/IngredientConverter.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Enum/AlarmStatus.java
  src/main/java/com/cook/cookapp/ingredient/entity/Enum/StorageType.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/repository/storedFoodsRepository.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/storedFoods/converter/storedFoodsConverter.java
  src/main/java/com/cook/cookapp/storedFoods/dto/req/storedFoodsDtoReq.java
  src/main/java/com/cook/cookapp/storedFoods/dto/res/storedFoodsDtoRes.java
  src/main/java/com/cook/cookapp/storedFoods/entity/Enum/AlarmStatus.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/UserRepository.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :hammer: Refactor

#9 ✨ Feat [#7] 로그인 관련 API 구현 완료
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/issue.yml
  build.gradle
  src/main/java/com/cook/cookapp/common/SwaggerConfig.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetail.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetailsService.java
  src/main/java/com/cook/cookapp/common/security/ExceptionHandlerFilter.java
  src/main/java/com/cook/cookapp/common/security/JwtAuthenticationFilter.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
  src/main/java/com/cook/cookapp/common/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/cook/cookapp/common/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/cook/cookapp/global/RootController.java
  src/main/java/com/cook/cookapp/ingredient/repository/storedFoodsRepository.java
  src/main/java/com/cook/cookapp/user/controller/KakaoLoginController.java
  src/main/java/com/cook/cookapp/user/controller/LoginController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/KakaoTokenResponseDto.java
  src/main/java/com/cook/cookapp/user/dto/res/KakaoUserInfoResponseDto.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/repository/UserRepository.java
  src/main/java/com/cook/cookapp/user/service/KakaoService.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/templates/login.html
Labels: :sparkles: Feature

#11 ✨ Feat [#10] 냉장고 API 구현.
  build.gradle
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
  src/main/java/com/cook/cookapp/common/validation/PageValidator.java
  src/main/java/com/cook/cookapp/common/validation/ValidPage.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/converter/IngredientConverter.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/repository/IngredientRepository.java
  src/main/java/com/cook/cookapp/ingredient/repository/storedFoodsRepository.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :sparkles: Feature

#13 ✨ Feat [#13] 사용자 API 구현. #13
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/recipe/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/KakaoTokenResponseDto.java
  src/main/java/com/cook/cookapp/recipe/dto/res/KakaoUserInfoResponseDto.java
  src/main/java/com/cook/cookapp/recipe/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/recipe/dto/res/UserProfileResponse.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/entity/ProfileImage.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/UserRepository.java
Labels: :sparkles: Feature

#15 :hammer: ref [#10] 냉장고 API 데이터 타입 수정
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/converter/IngredientConverter.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :hammer: Refactor

#19 [Deploy] 배포 Test
  src/main/resources/application-deploy.yml
  src/main/resources/application.yml
Labels: :earth_asia: Deploy

#21 :hammer: ref yml수정
  src/main/resources/application-deploy.yml
Labels: :earth_asia: Deploy

#22 :hammer: ref 수정 springboot 버전 수정
  build.gradle
Labels: :earth_asia: Deploy, :hammer: Refactor

#26 TEST
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
Labels: :earth_asia: Deploy

#27 🌏 Deploy [jwt Test]
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
Labels: :earth_asia: Deploy

#32 🔨 ref [#31] 사용자 API 수정
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :hammer: Refactor, :sparkles: Feature

#33 :earth_asia: Deploy [#31] #31배포
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy

#35 :sparkles: Feat [#34] 카카오 로그인 앱과 연동.
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/KakaoAccessTokenRequest.java
  src/main/resources/application-deploy.yml
Labels: :sparkles: Feature

#36 🌏 Deploy [#34] #34 배포
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/KakaoAccessTokenRequest.java
  src/main/resources/application-deploy.yml
Labels: :earth_asia: Deploy

#37 :sparkles: Feat [#34] 허용할 Origin 도메인 설정
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
Labels: :sparkles: Feature

#38 🌍 Deploy [#34] #34 배포
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
Labels: :earth_asia: Deploy

#41 🌍 Deploy [#39] #39 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeResponseDto.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/entity/RecipeIngredient.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/UserRepository.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy, :sparkles: Feature

#44 Deploy [#42] #42 배포
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeResponseDto.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy

#46 🔨 [ref] 레시피 API 수정
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
Labels: :hammer: Refactor, :sparkles: Feature

#47 Deploy [#45] #45 배포
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
Labels: :earth_asia: Deploy, :hammer: Refactor

#49 :hammer: Ref [#48] 오류 처리 관련 리펙토링
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/handler/UserHandler.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetailsService.java
  src/main/java/com/cook/cookapp/common/validation/PageValidator.java
  src/main/java/com/cook/cookapp/common/validation/ValidPage.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/user/controller/KakaoLoginController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/KakaoAccessTokenRequest.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :hammer: Refactor

#50 🌏 Deploy [#48] 오류 처리 관련 리펙토링 배포
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/handler/UserHandler.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetailsService.java
  src/main/java/com/cook/cookapp/common/validation/PageValidator.java
  src/main/java/com/cook/cookapp/common/validation/ValidPage.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/dto/req/IngredientDtoReq.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/user/controller/KakaoLoginController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/KakaoAccessTokenRequest.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :earth_asia: Deploy

#52 🔨 Ref [#51] 사용자,레시피 API 수정
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeResponseDto.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/dto/res/UserProfileResponse.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :hammer: Refactor, :sparkles: Feature

#53 🌏 Deploy [#51] 사용자,레시피 API 수정
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeResponseDto.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/dto/res/UserProfileResponse.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: :earth_asia: Deploy, :hammer: Refactor

#55 :hammer: Ref [#54] 잘못된 Merge 복구
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :hammer: Refactor

#56 🌍 Deploy [#54] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy

#58 [REF] 사용자,레시피 API 성공 처리 수정
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
Labels: :hammer: Refactor

#59 🌏 Deploy [#58] #58 배포
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
Labels: :earth_asia: Deploy

#61 :bug: fix [#60] 에러 응답 포맷 및 result 필드 일관성 수정
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/common/security/JwtAuthenticationFilter.java
  src/main/java/com/cook/cookapp/user/controller/KakaoLoginController.java
Labels: :bug: bug

#65 :sparkles: [#62] ChatBot 구현 (음식 레시피 추천), 사용자 음식 취향 입력/조회 API 구현
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/chatbot/controller/ChatbotController.java
  src/main/java/com/cook/cookapp/chatbot/dto/ChatbotResponse.java
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotService.java
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/cook/cookapp/chatbot/util/TastePreferenceValidator.java
  src/main/java/com/cook/cookapp/common/RestTemplateConfig.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :sparkles: Feature

#66 🌏 Deploy [#60,#62] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/chatbot/controller/ChatbotController.java
  src/main/java/com/cook/cookapp/chatbot/dto/ChatbotResponse.java
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotService.java
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/cook/cookapp/chatbot/util/TastePreferenceValidator.java
  src/main/java/com/cook/cookapp/common/RestTemplateConfig.java
  src/main/java/com/cook/cookapp/common/security/JwtAuthenticationFilter.java
  src/main/java/com/cook/cookapp/user/controller/KakaoLoginController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#68 :bug: [#67] JWT Bearer 접두사 처리 및 블랙리스트 로직 수정
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
Labels: :bug: bug

#64 [REF] 사용자,레시피 API 성공 처리 수정
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/req/PostDtoReq.java
  src/main/java/com/cook/cookapp/post/dto/res/PostDtoRes.java
  src/main/java/com/cook/cookapp/post/entity/Enum/Category.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :hammer: Refactor, :sparkles: Feature

#69 🌏 Deploy [#67] 수정사항 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/req/PostDtoReq.java
  src/main/java/com/cook/cookapp/post/dto/res/PostDtoRes.java
  src/main/java/com/cook/cookapp/post/entity/Enum/Category.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#72 :sparkles: Feat[#71] 게시글 API 기능 추가 (게시글 조회 API)
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
Labels: :sparkles: Feature

#74 :hammer: Ref[#73] 사용자 refresh API 오류 처리 수정
  src/main/java/com/cook/cookapp/apiPayload/ApiResponse.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
Labels: :hammer: Refactor

#75 🌏 Deploy [#73] 수정사항 배포
  src/main/java/com/cook/cookapp/apiPayload/ApiResponse.java
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
Labels: :earth_asia: Deploy, :hammer: Refactor, :sparkles: Feature

#77 :bug: Fix [#76] PostController에서 패키지 import 오류 수정
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :bug: bug

#78 🌏 PostController 파일 긴급 수정 배포
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :earth_asia: Deploy

#81 :hammer: Ref [#80] 공동구매 글,레시피 API 수정
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/req/PostDtoReq.java
  src/main/java/com/cook/cookapp/post/dto/res/PostDtoRes.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
Labels: :hammer: Refactor

#83 :sparkles: FEAT[#82] 레시피 API 기능 추가
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/entity/Enum/Category.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
Labels: :hammer: Refactor, :sparkles: Feature

#85 :hammer: Ref[#84] 레시피 API 수정
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
Labels: :hammer: Refactor

#86 Deploy [#80,#82,#84] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/req/PostDtoReq.java
  src/main/java/com/cook/cookapp/post/dto/res/PostDtoRes.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Enum/Category.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
Labels: :earth_asia: Deploy

#90 :sparkles: Feat[#89] 게시글 수정 , 상세 조회 API 생성
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
Labels: :sparkles: Feature

#91 Deploy [#89] 배포
  build.gradle
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/common/RedisCacheConfig.java
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/common/security/JwtAuthenticationFilter.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#93 :sparkles: Feat[#92] [FEAT] 게시글 좋아요,삭제, 사용자가 좋아요 한 글 조회 API 생성
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/controller/LikedPostController.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/LikedPostConverter.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/LikedPost.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/repository/LikedPostRepository.java
  src/main/java/com/cook/cookapp/post/service/LikedPostService.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/UserDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/UserRepository.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#95 :sparkles: Feat[#94] 닉네임 변경,게시글 검색 API 구현
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/entity/ProfileImage.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#96 :sparkles: Feat[#94] jwt토큰 에러처리 수정, redis 배포 설정
  src/main/java/com/cook/cookapp/apiPayload/ApiResponse.java
  src/main/java/com/cook/cookapp/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/com/cook/cookapp/common/security/JwtAuthenticationFilter.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/resources/application-deploy.yml
Labels: :sparkles: Feature

#99 :hammer: Ref[#98] redis 배포 설정
  src/main/java/com/cook/cookapp/common/RedisConfig.java
Labels: :hammer: Refactor

#100 🌏 Deploy [#98] 배포
  src/main/java/com/cook/cookapp/common/RedisConfig.java
Labels: :earth_asia: Deploy

#101 :hammer: Ref redis 관련 설정 수정
  src/main/resources/application-deploy.yml
Labels: :earth_asia: Deploy
