Repository capstone-cookings/BE, pull requests merged in 2025-04, with the labels that each got.

#103 :sparkles: Feat[#102] 프로필 사진 업로드 API, S3 관련 설정
  src/main/java/com/cook/cookapp/common/AmazonConfig.java
  src/main/java/com/cook/cookapp/common/AmazonS3Manager.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/repository/ProfileImageRepository.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :sparkles: Feature

#105 :hammer: Ref[#104] 게시글 검색 API 수정
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
Labels: :hammer: Refactor

#107 :hammer: Ref[#106] 게시글 좋아요 API 수정
  src/main/java/com/cook/cookapp/post/controller/LikedPostController.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/service/LikedPostService.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
Labels: :hammer: Refactor

#108 🌏 Deploy [#102,104,106] 배포
  src/main/java/com/cook/cookapp/common/AmazonConfig.java
  src/main/java/com/cook/cookapp/common/AmazonS3Manager.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/controller/LikedPostController.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/LikedPostService.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/java/com/cook/cookapp/user/converter/UserConverter.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/repository/ProfileImageRepository.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#110 :hammer: Ref[#109] 프로필 이미지 업로드 API 수정
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/user/entity/User.java
Labels: :hammer: Refactor

#111 🌏 Deploy [#109] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/user/entity/User.java
Labels: :earth_asia: Deploy

#114 🌏 Deploy [#112] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/ingredient/repository/IngredientRepository.java
  src/main/java/com/cook/cookapp/recipe/controller/RecipeController.java
  src/main/java/com/cook/cookapp/recipe/converter/RecipeConverter.java
  src/main/java/com/cook/cookapp/recipe/dto/req/RecipeDtoReq.java
  src/main/java/com/cook/cookapp/recipe/dto/res/RecipeDtoRes.java
  src/main/java/com/cook/cookapp/recipe/entity/Recipe.java
  src/main/java/com/cook/cookapp/recipe/entity/RecipeImage.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeImageRepository.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeIngredientRepository.java
  src/main/java/com/cook/cookapp/recipe/repository/RecipeRepository.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeService.java
  src/main/java/com/cook/cookapp/recipe/service/RecipeServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#116 :sparkles: Feat[#115] 게시글 이미지 업로드 API 구현
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/entity/PostImage.java
  src/main/java/com/cook/cookapp/post/repository/PostImageRepository.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :hammer: Refactor, :sparkles: Feature

#117 🌏 Deploy [#115] 배포
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/Post.java
  src/main/java/com/cook/cookapp/post/entity/PostImage.java
  src/main/java/com/cook/cookapp/post/repository/PostImageRepository.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#118 ✨ Feat [#88] 채팅방/채팅 기능 구현(메시지 알림 제외)
  build.gradle
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketAuthInterceptor.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketConfig.java
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/converter/ChatConverter.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/entity/ChatMessage.java
  src/main/java/com/cook/cookapp/chat/entity/ChatNotification.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoom.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoomParticipant.java
  src/main/java/com/cook/cookapp/chat/redis/ChatRoomRedisService.java
  src/main/java/com/cook/cookapp/chat/repository/ChatMessageRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomParticipantRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
  src/main/java/com/cook/cookapp/chat/socket/ChatMessageHandler.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatEnterLeaveRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatMessageSocketRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatReadEventRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/res/ChatRoomMemberListResponse.java
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetail.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
Labels: :hammer: Refactor, :sparkles: Feature

#119 Revert "✨ Feat [#88] 채팅방/채팅 기능 구현(메시지 알림 제외)"
  build.gradle
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketAuthInterceptor.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketConfig.java
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/converter/ChatConverter.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/entity/ChatMessage.java
  src/main/java/com/cook/cookapp/chat/entity/ChatNotification.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoom.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoomParticipant.java
  src/main/java/com/cook/cookapp/chat/redis/ChatRoomRedisService.java
  src/main/java/com/cook/cookapp/chat/repository/ChatMessageRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomParticipantRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
  src/main/java/com/cook/cookapp/chat/socket/ChatMessageHandler.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatEnterLeaveRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatMessageSocketRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatReadEventRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/res/ChatRoomMemberListResponse.java
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetail.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
Labels: :hammer: Refactor

#120 :hammer: Ref [#88] 불필요한 세미콜론 제거, ChatUnreadBroadcast 불필요 필드 제거
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
Labels: :hammer: Refactor

#123 :hammer: Ref[#122] 챗봇 레시피 반환 형식 , 게시글 조회 API , 게시글 등록 API 수정
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/LikedPost.java
  src/main/java/com/cook/cookapp/post/repository/LikedPostRepository.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
Labels: :hammer: Refactor

#124 🌏 Deploy [#88,122] 배포
  build.gradle
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketAuthInterceptor.java
  src/main/java/com/cook/cookapp/chat/config/WebSocketConfig.java
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/converter/ChatConverter.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/entity/ChatMessage.java
  src/main/java/com/cook/cookapp/chat/entity/ChatNotification.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoom.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoomParticipant.java
  src/main/java/com/cook/cookapp/chat/redis/ChatRoomRedisService.java
  src/main/java/com/cook/cookapp/chat/repository/ChatMessageRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomParticipantRepository.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
  src/main/java/com/cook/cookapp/chat/socket/ChatMessageHandler.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatEnterLeaveRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatMessageSocketRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/req/ChatReadEventRequest.java
  src/main/java/com/cook/cookapp/chat/socket/dto/res/ChatRoomMemberListResponse.java
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/cook/cookapp/common/RedisConfig.java
  src/main/java/com/cook/cookapp/common/security/CustomUserDetail.java
  src/main/java/com/cook/cookapp/common/security/JwtTokenProvider.java
  src/main/java/com/cook/cookapp/common/security/SecurityConfig.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/entity/LikedPost.java
  src/main/java/com/cook/cookapp/post/repository/LikedPostRepository.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/java/com/cook/cookapp/user/service/UserService.java
Labels: :earth_asia: Deploy

#126 :hammer: Ref[#125] 게시글 좋아요 로직 수정
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :hammer: Refactor

#127 🌏 Deploy [#125] 배포
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
Labels: :earth_asia: Deploy

#129 ✨ Feat [#88] 채팅방 생성 때 유효값 설정, 메시지 조회 (페이징, 무한 스크롤 버전) 구현
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/repository/ChatMessageRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
Labels: :hammer: Refactor, :sparkles: Feature

#130 🌏 Deploy [#88] 채팅 기능 배포(FCM 알림 제외)
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/repository/ChatMessageRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
Labels: :earth_asia: Deploy

#132 :sparkles: Feat[#131] 검색기록 관련 api 구현
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/post/controller/SearchHistoryController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/converter/SearchHistoryConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/dto/res/SearchResDto.java
  src/main/java/com/cook/cookapp/post/entity/SearchHistory.java
  src/main/java/com/cook/cookapp/post/repository/SearchHistoryRepository.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/SearchHistoryService.java
  src/main/java/com/cook/cookapp/post/service/SearchHistoryServiceImpl.java
  src/main/java/com/cook/cookapp/user/entity/User.java
Labels: :sparkles: Feature

#134 :hammer: Ref[#133] 게시글 이미지 업로드 로직 수정
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
Labels: :hammer: Refactor

#135 🌏 Deploy [#131, 133] 배포
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/controller/SearchHistoryController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/converter/SearchHistoryConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/dto/res/SearchResDto.java
  src/main/java/com/cook/cookapp/post/entity/SearchHistory.java
  src/main/java/com/cook/cookapp/post/repository/SearchHistoryRepository.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/SearchHistoryService.java
  src/main/java/com/cook/cookapp/post/service/SearchHistoryServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/S3Controller.java
  src/main/java/com/cook/cookapp/user/entity/User.java
Labels: :earth_asia: Deploy

#137 :hammer: Ref[#136] 상세 게시글 조회 postImage 반환 방식 수정
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
Labels: :hammer: Refactor

#138 🌏 Deploy [#136] 배포
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
Labels: :earth_asia: Deploy

#140 :hammer: Ref[#139] 챗봇 레시피 반환 형식 (다른 레시피 추천API) 수정
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
Labels: :hammer: Refactor

#141 🌏 Deploy [#139] 배포
  src/main/java/com/cook/cookapp/chatbot/service/ChatbotServiceImpl.java
Labels: :earth_asia: Deploy

#145 :hammer: Ref[#144] 게시글 검색 API 수정
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
Labels: :hammer: Refactor

#146 :hammer: Ref [#88] 프론트 요구 사항 반영
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoom.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
Labels: :hammer: Refactor

#147 🌏 Deploy [#144,#88] 배포
  src/main/java/com/cook/cookapp/chat/controller/ChatController.java
  src/main/java/com/cook/cookapp/chat/dto/req/ChatDtoReq.java
  src/main/java/com/cook/cookapp/chat/dto/res/ChatDtoRes.java
  src/main/java/com/cook/cookapp/chat/entity/ChatRoom.java
  src/main/java/com/cook/cookapp/chat/repository/ChatRoomRepository.java
  src/main/java/com/cook/cookapp/chat/service/ChatService.java
  src/main/java/com/cook/cookapp/chat/service/ChatServiceImpl.java
  src/main/java/com/cook/cookapp/post/controller/PostController.java
  src/main/java/com/cook/cookapp/post/converter/PostConverter.java
  src/main/java/com/cook/cookapp/post/dto/res/PostResDto.java
  src/main/java/com/cook/cookapp/post/repository/PostRepository.java
  src/main/java/com/cook/cookapp/post/service/LikedPostServiceImpl.java
  src/main/java/com/cook/cookapp/post/service/PostService.java
  src/main/java/com/cook/cookapp/post/service/PostServiceImpl.java
Labels: :earth_asia: Deploy

#149 :sparkles: Feat[#148] 식재료 이미지 추가 API, 신고 API, 유저 등급 추가, 칭찬기능 틀 잡기
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/converter/IngredientConverter.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/entity/IngredientImage.java
  src/main/java/com/cook/cookapp/ingredient/repository/IngredientImageRepository.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/ComplimentController.java
  src/main/java/com/cook/cookapp/user/controller/ReportController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/ReportDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/Compliment.java
  src/main/java/com/cook/cookapp/user/entity/ComplimentType.java
  src/main/java/com/cook/cookapp/user/entity/Report.java
  src/main/java/com/cook/cookapp/user/entity/ReportType.java
  src/main/java/com/cook/cookapp/user/entity/TrustLevel.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/ComplimentRepository.java
  src/main/java/com/cook/cookapp/user/repository/ReportRepository.java
  src/main/java/com/cook/cookapp/user/service/ComplimentService.java
  src/main/java/com/cook/cookapp/user/service/ComplimentServiceImpl.java
  src/main/java/com/cook/cookapp/user/service/ReportService.java
  src/main/java/com/cook/cookapp/user/service/ReportServiceImpl.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :sparkles: Feature

#150 🌏 Deploy [#148] 배포
  README.md
  src/main/java/com/cook/cookapp/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/cook/cookapp/global/util/AmazonS3Util.java
  src/main/java/com/cook/cookapp/ingredient/controller/IngredientController.java
  src/main/java/com/cook/cookapp/ingredient/converter/IngredientConverter.java
  src/main/java/com/cook/cookapp/ingredient/dto/res/IngredientDtoRes.java
  src/main/java/com/cook/cookapp/ingredient/entity/Ingredient.java
  src/main/java/com/cook/cookapp/ingredient/entity/IngredientImage.java
  src/main/java/com/cook/cookapp/ingredient/repository/IngredientImageRepository.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientService.java
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
  src/main/java/com/cook/cookapp/user/controller/ComplimentController.java
  src/main/java/com/cook/cookapp/user/controller/ReportController.java
  src/main/java/com/cook/cookapp/user/controller/UserController.java
  src/main/java/com/cook/cookapp/user/dto/req/ReportDtoReq.java
  src/main/java/com/cook/cookapp/user/dto/res/UserDtoRes.java
  src/main/java/com/cook/cookapp/user/entity/Compliment.java
  src/main/java/com/cook/cookapp/user/entity/ComplimentType.java
  src/main/java/com/cook/cookapp/user/entity/Report.java
  src/main/java/com/cook/cookapp/user/entity/ReportType.java
  src/main/java/com/cook/cookapp/user/entity/TrustLevel.java
  src/main/java/com/cook/cookapp/user/entity/User.java
  src/main/java/com/cook/cookapp/user/repository/ComplimentRepository.java
  src/main/java/com/cook/cookapp/user/repository/ReportRepository.java
  src/main/java/com/cook/cookapp/user/service/ComplimentService.java
  src/main/java/com/cook/cookapp/user/service/ComplimentServiceImpl.java
  src/main/java/com/cook/cookapp/user/service/ReportService.java
  src/main/java/com/cook/cookapp/user/service/ReportServiceImpl.java
  src/main/java/com/cook/cookapp/user/service/UserServiceImpl.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
Labels: :earth_asia: Deploy

#151 :sparkles: Feat[#148] 식재료 이미지 추가 API, 신고 API, 유저 등급 추가, 칭찬기능 틀 잡기
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :sparkles: Feature

#152 🌏 Deploy [#148] 배포
  src/main/java/com/cook/cookapp/ingredient/service/IngredientServiceImpl.java
Labels: :earth_asia: Deploy
